# -*- coding: utf-8 -*-
"""Retails.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgsqFe-_mi-aotFr1cjQ3ANjGYrzixpI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
from statsmodels.tsa.seasonal import seasonal_decompose
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/mock_kaggle.csv')
df.head()

df.shape

df.isnull().sum()

df.info()

df.describe()

sns.pairplot(df)

df['data'] = pd.to_datetime(df['data'])
df = df.sort_values('data').reset_index(drop=True)
df['weekday'] = df['data'].dt.weekday
df['month'] = df['data'].dt.month
df.set_index('data', inplace=True)
df.head()

# Daily sales
plt.figure()
df['venda'].plot(title="Daily Sales (venda)")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()

# Rolling averages (7-day & 30-day)
roll = pd.DataFrame({
    'venda': df['venda'],
    'venda_7d_ma': df['venda'].rolling(7, min_periods=1).mean(),
    'venda_30d_ma': df['venda'].rolling(30, min_periods=1).mean(),
})
plt.figure()
roll.plot(ax=plt.gca(), title="Sales with Rolling Averages (7d & 30d)")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()

# Monthly sales
monthly = df['venda'].resample('M').sum()
plt.figure()
monthly.plot(title="Monthly Sales (Sum of venda)")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()

try:
    y = df['venda'].asfreq('D').interpolate()
    decomp = seasonal_decompose(y, model='additive', period=7)

    plt.figure()
    pd.Series(decomp.trend, index=y.index).plot(title="Decomposition - Trend")
    plt.xlabel("Date"); plt.ylabel("Trend"); plt.tight_layout(); plt.show()

    plt.figure()
    pd.Series(decomp.seasonal, index=y.index).plot(title="Decomposition - Seasonal (Weekly)")
    plt.xlabel("Date"); plt.ylabel("Seasonality"); plt.tight_layout(); plt.show()

    plt.figure()
    pd.Series(decomp.resid, index=y.index).plot(title="Decomposition - Residuals")
    plt.xlabel("Date"); plt.ylabel("Residual"); plt.tight_layout(); plt.show()

except Exception as e:
    print("Seasonal decomposition skipped:", e)

# Inventory over time
plt.figure()
df['estoque'].plot(title="Inventory (estoque) Over Time")
plt.xlabel("Date")
plt.ylabel("Stock Level")
plt.tight_layout()
plt.show()

# Price over time
plt.figure()
df['preco'].plot(title="Price (preco) Over Time")
plt.xlabel("Date")
plt.ylabel("Price")
plt.tight_layout()
plt.show()

# Dual-axis plot: Sales vs. Price
fig, ax1 = plt.subplots()
ax1.plot(df.index, df['venda'])
ax1.set_xlabel("Date")
ax1.set_ylabel("Sales (venda)")
ax1.set_title("Sales vs Price (Dual Axis)")

ax2 = ax1.twinx()
ax2.plot(df.index, df['preco'])
ax2.set_ylabel("Price (preco)")

fig.tight_layout()
plt.show()

month_weekday = (
    df.reset_index()
      .pivot_table(index='month', columns='weekday', values='venda', aggfunc='mean')
      .sort_index()
)

plt.figure()
plt.imshow(month_weekday.values, aspect='auto')
plt.title("Heatmap: Mean Sales by Month (rows) x Weekday (cols)")
plt.xlabel("Weekday (0=Mon ... 6=Sun)")
plt.ylabel("Month (1-12)")
plt.colorbar(label="Mean Sales")
plt.tight_layout()
plt.show()

month_weekday

corr = df[['venda', 'estoque', 'preco']].corr()

plt.figure()
plt.imshow(corr.values, interpolation='nearest')
plt.title("Correlation Matrix (venda, estoque, preco)")
plt.xticks(range(len(corr.columns)), corr.columns, rotation=45)
plt.yticks(range(len(corr.index)), corr.index)
plt.colorbar()
plt.tight_layout()
plt.show()

corr

# Avoid log(0)
sales_clipped = df['venda'].clip(lower=1).astype(float)
price_clipped = df['preco'].clip(lower=1e-6).astype(float)

log_sales = np.log(sales_clipped)
log_price = np.log(price_clipped)

# log(Sales) = a + b*log(Price)
b, a = np.polyfit(log_price, log_sales, 1)

plt.figure()
plt.scatter(log_price, log_sales)
xline = np.linspace(log_price.min(), log_price.max(), 100)
plt.plot(xline, a + b * xline)
plt.xlabel("log(Price)")
plt.ylabel("log(Sales)")
plt.title("Log-Log Regression: Sales vs Price (Elasticity)")
plt.tight_layout()
plt.show()

print(f"Estimated price elasticity: {b:.3f}")

monthly_summary = pd.DataFrame({
    'sales_sum': df['venda'].resample('M').sum(),
    'sales_mean': df['venda'].resample('M').mean(),
    'price_mean': df['preco'].resample('M').mean(),
    'stock_mean': df['estoque'].resample('M').mean(),
})

monthly_summary.head()

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Prepare monthly data for forecasting
sales_monthly = df['venda'].resample('M').sum()

# Split into train/test (e.g., last 6 months as test)
train = sales_monthly.iloc[:-6]
test = sales_monthly.iloc[-6:]

# Fit ARIMA(p,d,q) model (you can adjust parameters)
model = ARIMA(train, order=(1,1,1))
model_fit = model.fit()

# Forecast the next 6 periods
forecast = model_fit.forecast(steps=6)
forecast.index = test.index

# Plot actual vs forecast
plt.figure()
plt.plot(train.index, train, label='Train')
plt.plot(test.index, test, label='Actual')
plt.plot(forecast.index, forecast, label='Forecast', linestyle='--')
plt.legend()
plt.title("ARIMA Forecast vs Actual Sales")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()

mae = mean_absolute_error(test, forecast)
rmse = np.sqrt(mean_squared_error(test, forecast))

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Root Mean Square Error (RMSE): {rmse:.2f}")

# Refit model on full series
final_model = ARIMA(sales_monthly, order=(1,1,1))
final_fit = final_model.fit()

future_forecast = final_fit.forecast(steps=12)

plt.figure()
plt.plot(sales_monthly.index, sales_monthly, label='Historical')
plt.plot(future_forecast.index, future_forecast, label='Future Forecast', linestyle='--')
plt.legend()
plt.title("12-Month ARIMA Sales Forecast")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.tight_layout()
plt.show()

future_forecast